services:
  app:
    build: .
    container_name: temple_app
    ports:
      - "3002:3002"
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DB_HOST: mysql
      DB_PASSWORD: rootpassword
    restart: always

  mysql:
    image: mysql:8
    container_name: temple_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: temple_db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: