apiVersion: apps/v1
kind: Deployment
metadata:
  name: temple-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temple-app
  template:
    metadata:
      labels:
        app: temple-app
    spec:
      containers:
        - name: temple-app
          image: sanjaimagilan/temple_app:latest
          ports:
            - containerPort: 3002

          envFrom:
            - secretRef:
                name: temple-secret

          env:
            - name: DB_HOST
              value: mysql-service
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: temple_user